### ISSUE TITLE
REQUEST: New Contributor for abe-101

### ISSUE THREAD

**Issue by abe-101** [Schrodinger-Hat/community#10]
### GitHub Username

abe-101

### Discord Username

abe#5755

### Requirements

- [X] I have reviewed the community membership guidelines
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Schrödinger Hat projects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are actual contributors of the community

### Sponsor 1

@Wabri

### Sponsor 2

@TheJoin95

### List of contributions to the Schrödinger Hat community

- https://github.com/Schrodinger-Hat/youtube-to-anchorfm/pull/46
- https://github.com/Schrodinger-Hat/youtube-to-anchorfm/pull/42
- https://github.com/Schrodinger-Hat/youtube-to-anchorfm/pull/37
- https://github.com/Schrodinger-Hat/youtube-to-anchorfm/pull/36
- https://github.com/Schrodinger-Hat/youtube-to-anchorfm/pull/35
- https://github.com/Schrodinger-Hat/youtube-to-anchorfm/pull/34
- https://github.com/Schrodinger-Hat/youtube-to-anchorfm/pull/26
- https://github.com/Schrodinger-Hat/youtube-to-anchorfm/issues/41
- https://github.com/Schrodinger-Hat/youtube-to-anchorfm/issues/32

**Comment by Wabri** [comment]
+1

**Comment by TheJoin95** [comment]
+1

**Comment by 404answernotfound** [comment]
+1

**Comment by Wabri** [comment]
Welcome to Schrödinger Hat community :1st_place_medal:
