### ISSUE TITLE
REQUEST: New Contributor for Readpato

### ISSUE THREAD

**Issue by Readpato** [Schrodinger-Hat/community#13]
### GitHub Username

@Readpato

### Discord Username

Readpato#8964

### Requirements

- [X] I have reviewed the community membership guidelines
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Schrödinger Hat projects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are actual contributors of the community

### Sponsor 1

@Wabri

### Sponsor 2

@nicpuppa

### List of contributions to the Schrödinger Hat community

- PRs reviewed / authored
    - [chore: Edit headline with new text content (fix: #20)](https://github.com/Schrodinger-Hat/schrodinger-hat-website/pull/29)
    - [fix: Repair Grusp broken logo on event page (fix: #21) #30](https://github.com/Schrodinger-Hat/schrodinger-hat-website/pull/30)
    - [docs: Create pull request template (fix: #11) #32](https://github.com/Schrodinger-Hat/schrodinger-hat-website/pull/32)
    - [docs: Update issues template (fix:#12) #33](https://github.com/Schrodinger-Hat/schrodinger-hat-website/pull/33)
- Projects I am involved with
    - [Schrödinger Hat Website](https://github.com/Schrodinger-Hat/schrodinger-hat-website)

**Comment by 404answernotfound** [comment]
Welcome to the contribs fam! 👯

**Comment by TheJoin95** [comment]
✅ Yes yes and yes!

Welcome to Schrodinger Hat 🥳

**Comment by nicpuppa** [comment]
Welcome @Readpato !

**Comment by davideimola** [comment]
👍 also for me!

**Comment by Wabri** [comment]
+1

**Comment by Readpato** [comment]
Thanks everyone for the warm welcome <3

**Comment by Wabri** [comment]
Welcome Pato to the organization :1st_place_medal:
