### ISSUE TITLE
REQUEST: New Contributor for ossan-dev

### ISSUE THREAD

**Issue by ossan-dev** [Schrodinger-Hat/community#14]
### GitHub Username

ossan-dev

### Discord Username

ossan#2971

### Requirements

- [X] I have reviewed the community membership guidelines
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Schrödinger Hat projects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are actual contributors of the community

### Sponsor 1

@wabri

### Sponsor 2

@davideimola

### List of contributions to the Schrödinger Hat community

- events organization

**Comment by TheJoin95** [comment]
LGTM

**Comment by davideimola** [comment]
👍🏻

**Comment by Wabri** [comment]
+1

**Comment by 404answernotfound** [comment]
👍

**Comment by davideimola** [comment]
Great! Welcome @ossan-dev!
