### ISSUE TITLE
REQUEST: New Contributor for @LobeTia

### ISSUE THREAD

**Issue by LobeTia** [Schrodinger-Hat/community#15]
### GitHub Username

LobeTia

### Discord Username

LobeTia

### Requirements

- [X] I have reviewed the community membership guidelines
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Schrödinger Hat projects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are actual contributors of the community

### Sponsor 1

@wabri

### Sponsor 2

@nicpuppa

### List of contributions to the Schrödinger Hat community

- Scouting per apertura associazione
- Eventi SH in Nana Bianca

**Comment by TheJoin95** [comment]
✅

**Comment by nicpuppa** [comment]
👍🏻

**Comment by Wabri** [comment]
:+1:

**Comment by Readpato** [comment]
Let's gooooo!

**Comment by davideimola** [comment]
Absolutely yes 👍🏻

**Comment by Wabri** [comment]
Add as "contributor" on discord, invite as member to the organization
